name = "supermeno"
main = "_worker.js"
compatibility_date = "2024-09-23"
compatibility_flags = [ "nodejs_compat" ]

keep_vars = true

[vars]
UUID = ""
PASSWORD = "galaxy-tunnel"
MASK_PAGE = "true"
WS_PATH = "galaxy-tunnel"
PROXYIP = "cdn-b100.xn--b6gac.eu.org"

DNS_RESOLVER_URL = "https://cloudflare-dns.com/dns-query"
